const mania_cafes_data = [
  {
    name: '타짜도르 도곡점',
    logo: 'https://cdn.imweb.me/upload/S201812145c13535647d46/5c174cf2c3395.png',
    address: '서울 강남구 남부순환로 2753 롯데시네마 도곡 1층',
    sido: '서울특별시',
    gungu: '강남구',
    dong: '도곡동',
    subway: '매봉역',
    tags: '이탈리아',
    description:
      '이태리 로마 타짜도르 카페와 정식 라이선스를 체결한 매장입니다.',
    'images.0':
      'https://ldb-phinf.pstatic.net/20201028_220/1603869980825o0iyA_JPEG/_thEhTQwh-u08UrfG4SaGBB6.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20201023_6%2F1603382199246GkXES_JPEG%2FoQ1iUCEmosX_JDKaO8yWALLy.jpg',
  },
  {
    name: '리얼빈 로스팅하우스',
    logo: 'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20170222_267%2F1487691212592Rnctk_JPEG%2F186172406352513_0.jpeg',
    address: '서울 강남구 자곡로7길 22-2 b1 리얼빈 로스팅하우스',
    sido: '서울특별시',
    gungu: '강남구',
    dong: '자곡동',
    tags: '로스터리,가성비',
    description:
      '원두커피, 더치커피 전문업체 리얼빈 로스팅하우스가 여러분을 환영합니다.\n저희의 커피를 최고라고 말하는 자만은 하지 않겠습니다.\n다만, 회사의 모토인 가성비에 있어 여러분을 실망시켜 드리지 않음을 약속드립니다.\n\n좋은 가격에 드리는 고품질의 원두, 진하게 내려 맛과 향미가 살아있는 콜드브루.\n여러분의 삶에 작은 쉼표를 찍어드릴수 있기를 희망합니다.\n\nBe Real, Be Happy.\nRealBean Roasting House',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMjA3MjdfMTc5%2FMDAxNjU4ODk4MzcwMzMy._gJjo5do3VXfVX9l8SGymqTRqFx7cx05gCuDE9y0Bukg.LydRFEl0tyk55wNGUIUOPbjR81cIUXdPaubkcooM7H4g.JPEG%2Fupload_38c9dce57fdf101996c738f88e673051.jpeg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMjA3MjdfNjQg%2FMDAxNjU4ODk4MzcwMDc2.sRF8ASoQ1H6pnZkP1Ccl5KWCb1Je-mpXLGry1fZcC8sg.QQPooqmQfAq7UKx1qRh6B3mRTlHW3MAjplr2qVs6k_gg.JPEG%2Fupload_09a9843a8baffab2c6accde17a1d792d.jpeg',
  },
  {
    name: '커피스니퍼 센터필드점',
    address: '서울 강남구 테헤란로 231 센터필드 지상 2층 E207호 커피스니퍼',
    sido: '서울특별시',
    gungu: '강남구',
    dong: '역삼동',
    subway: '역삼역',
    wifi: 'O',
    parking: 'O',
    tags: '로스터리',
    description:
      '커피 스니퍼 (Koffee Sniffer)는 커피를 사랑하는 여러 바리스타들이 모여 심혈을 기울여 만든 로스터리 브랜드 입니다. 커피 한 잔이 어제보다 나은 오늘을 만들 수 있다 믿고, 향기로운 커피를 끊임없이 탐닉하고 연구합니다.',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTExMjdfMjE2%2FMDAxNjM3OTkyNjcyMTUy.wCCl0MpVoXC8uFJ2PeP2ltLO0rpk868tWzTadDWCA_Mg.V5_Xzk7ahMVIGwoGnDcaOKg6nVtGdKTq_2B-_nW0CsUg.JPEG.jainlee_star%2Foutput_1278544775.jpg',
    'images.1':
      'https://ldb-phinf.pstatic.net/20210712_172/1626053073569zulLS_JPEG/7WYwX4lsK2GDQxDP9_NeXId0.jpeg.jpg',
  },
  {
    name: '인텔리젠시아커피 디스트리뷰터 MH',
    address:
      '서울 강남구 강남대로146길 33 1층, 신사역 1번출구 287m , 학동공원 근처',
    sido: '서울특별시',
    gungu: '강남구',
    dong: '논현동',
    subway: '신사역',
    wifi: 'O',
    parking: 'O',
    tags: '스페셜티커피',
    description:
      "※ 주차가능( 방문전 확인 전화 ) ※\n\n*USA 시카고에서 로스팅한 스페셜티 커피 ' 인텔리젠시아 ' 는 스페셜티 커피 산업을 주도하는 브랜드로서 옳은 방향성으로 커피를 만듭니다.\n\n*우리는 Thoughtfully sourced and roasted by intelligentsia coffee 인텔리젠시아 커피를 소개합니다.",
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210309_76%2F1615249734227LzJNj_JPEG%2FPBlioK9WvH4_Bf1Deko5Iq63.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210618_33%2F1623996457196N68fG_JPEG%2FFh_FE09hRJdnxYc25c5QgvD_.jpg',
  },
  {
    name: '벙커컴퍼니 압구정점',
    address: '서울 강남구 언주로167길 23 단독주택 1, 2층',
    sido: '서울특별시',
    gungu: '강남구',
    dong: '신사동',
    subway: '압구정역',
    wifi: 'O',
    tags: '로스터리,스페셜티커피,대회 수상',
    description:
      '(주)벙커컴퍼니\n\n2019 Swift Latte Art Match Sponsor\n2019 Korea Barista Awards Sponsor\n2019 Korea Brewers Cup (국가대표 선발전) Sponsor\n2020 Korea National Barista (국가대표 선발전) Sponsor\n2022 Korea National Barista & KCIGS (국가대표선발전) Sponsor.\n\nAWARD\n2011 Espresso Throw Down 1위.\n2012 Barista Association of Korea Barista Championship 1위.\n2020 Korea Barista Awards Espresso 대상.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210924_32%2F1632452759303yTAj8_JPEG%2FWf0RbPgaIKGhViH8TgBNhjlQ.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMzAxMDVfMTAy%2FMDAxNjcyOTE0MTc3OTQ1.PTJL_02MiSJk-uMHHcImeip0HAVEIAwQqWBUiPeA5HEg.2967bZW7DUSeyxXePGnSCNAYEsupURN74tuu6x4qhKwg.JPEG%2F1D4CD5BF-9005-419B-9D4B-AC1D8573B159.jpeg',
  },
  {
    name: '스몰 배치 서울(Small Batch Seoul)',
    address: '서울 강남구 언주로168길 6-7',
    sido: '서울특별시',
    gungu: '강남구',
    dong: '신사동',
    subway: '압구정역',
    wifi: 'O',
    pet: 'O',
    tags: '호주',
    description:
      'Small Batch Roasting co.의 국내 공식 수입원 호주 멜버른 스페셜티 커피 Small Batch Australia 의 서울 쇼룸\n\n호주 멜버른의 대표적인 마이크로로스터 스몰배치의 서울 쇼룸. 커피 음료에 집중한 메뉴 구성으로, 필터커피와 피넛버터크림이 올려진 스피키가 시그니처. 도산공원 인근 주택가 반지하에 아담하게 자리하고 있어 좌석 수는 적은 편이지만, 호주 커피의 맛을 즐기려는 이들이 많이 찾는다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fmyplace-phinf.pstatic.net%2F20220401_219%2F1648813670578Rzl9m_JPEG%2Fupload_cc7a87defa285f3d439634f22ce60d38.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA5MTFfMjQ4%2FMDAxNjMxMzYwNDc0NDk4.6huibV-AjQHyUVQ4F98dCkytoFJwrwaG8uMhaolHdEog.V9luLcF3DkY7pH62CXxV38ronm3m-0DJEp872iLa6Agg.JPEG.rypher%2FBED41C9B-948B-4BC9-8D34-F2EBF61DF29E.jpg',
  },
  {
    name: '커피몽타주',
    address: '서울 강동구 올림픽로48길 23-12 1층',
    sido: '서울특별시',
    gungu: '강동구',
    dong: '성내동',
    subway: '강동구청역',
    wifi: 'O',
    tags: '로스터리',
    description:
      '로스팅 컴퍼니 커피몽타주에서 운영하는 카페로 커피몽타주의 대표 에스프레소 블렝딩 A Bittersweet Life로 추출하는 에스프레소 베리에이션 음료들과 더불어 다양한 커피 산지들의 싱글오리진 브루잉 커피들도 맛볼 수 있다. 다양한 커피 추출도구와 원두도 판매하고 있다.',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTAzMDNfNiAg%2FMDAxNjE0NzUzMTE4NjY2.HciDulxarPnLfH02k-g1Kv7CtrK1C-SKyuqLCKGLDUAg.3gmmsaUeR1YrENCDPdjfsBIaI9mt6-p1a3vFsarxCH8g.JPEG.gofl9387%2FIMG_3464.JPG',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200104_222%2F1578146510582sjBit_JPEG%2FU88ytcKz5B4v5bW7Rtgm8Rfn.jpgg',
  },
  {
    name: '애크로매틱 커피 컴퍼니',
    address: '서울 강동구 성내로14길 37',
    sido: '서울특별시',
    gungu: '강동구',
    dong: '성내동',
    subway: '강동구청역',
    parking: 'O',
    tags: '스페셜티커피',
    description:
      '스페셜티 커피 전문점으로 에스프레소와 브루잉 커피가 숙련된 바리스타를 통해 서비스된다. 매장에 별도의 공간을 두어 로스팅하고 있으며, 강배전 커피도 스페셜티 커피로 사용하고 있다는 점이 특징. 다양한 산지의 싱글 오리진 커피를 매년 지속해서 소개하고 있다.',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA2MjlfNzEg%2FMDAxNjU2NTEwMDcyMTMw.R2RDqpGe_vyeHYaKmRYHnwcVYVp2Mtub9hiBX6qiRIMg.oYwK8vqAsxYKfBf160OntCvW4b5JutPuNVgQxPuZAkcg.JPEG.smilefaceu%2F20220628%25A3%25DF192657.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMzAxMDhfMTMg%2FMDAxNjczMTgzMTc3NjQx.7HMGTRxtsuTMzTEQnrpC1XqPLO57JYBiW33Q9oZw4Kcg.ev6PZuvVOBEW3GPuCLj6q_Bp2WL5Iwo9wE_emLI6m2og.JPEG%2F3C537B5A-59E6-4F22-BA8E-4AE1434657FE.jpeg',
  },
  {
    name: '맥그레고르',
    address: '서울 강동구 풍성로 99 1층 카페 맥그레고르',
    sido: '서울특별시',
    gungu: '강동구',
    dong: '성내동',
    subway: '강동구청역',
    wifi: 'O',
    pet: 'O',
    tags: '석탄단',
    description: '신 맛 없는 석탄단 카페 맥그레고르',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTExMTFfOTUg%2FMDAxNjM2NjA4NTYzODc0.d1yztIhoQwgUzjcTyAZyl-mbZPLqKGkhymgl2fA8_EMg.Macd01On8c-7-FugAVUbHfUKHL1ZVIYpNAiSW6TspKMg.JPEG.eatbbeum%2FIMG_4561.JPG',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220219_86%2F1645282189239r4AJ2_JPEG%2FE730BF1A-7B5C-4960-8BB4-7823C2AB0BC1.jpeg',
  },
  {
    name: '컴 폴 커피',
    address: '서울 강북구 덕릉로 130 1층 컴 폴 커피',
    sido: '서울특별시',
    gungu: '강북구',
    dong: '번동',
    subway: '수유역',
    wifi: 'O',
    pet: 'O',
    description:
      '안녕하세요 컴 폴 커피 입니다.\n컴 폴 커피는 클래식한 블랜딩 원두로 묵직하며, 부드럽게 넘어가는 에스프레소를 제공 합니다.\n오셔서 맛있게 즐겨주세요.\n여러분 커피 마시러 오세요 Come For Coffee',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA4MDRfMjY4%2FMDAxNjI4MDQyNTU3NTMy.thgWUq68D4GmJOrwUl2lHLlD5zEWOCQ_nWf9sa0EN9Mg.5jzmCzV2-qYBuiERNylP4BEl4eJQwqepjijr2YH_sgQg.JPEG.macciattocompany%2F2_%25BF%25DC%25B0%25FC.jpg',
    'images.1':
      'https://ldb-phinf.pstatic.net/20210429_10/1619677827016rvmMt_JPEG/rCW4_lBFgxbtDhGQyB0fmqUJ.jpeg.jpg',
  },
  {
    name: '리키커피숍',
    address: '서울 강서구 공항대로8길 41',
    sido: '서울특별시',
    gungu: '강서구',
    dong: '공항동',
    subway: '송정역',
    wifi: 'O',
    pet: 'O',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMTJfNTYg%2FMDAxNjY1NTgyNTM3NTk2.o5XOKQtKK3jFVE7LtS_3AM2xP6Vjm7ySEU2feOIlXxwg.Lw9wNARiNUPNAHVBBpW4ZDd_xt4shMrJilERSPY2cXog.JPEG.grummy%2Foutput_483114440.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20221005_226%2F1664950698062uw2qv_JPEG%2F60A524B7-56B1-4FA4-BE50-22A1F3DBFA98.jpeg',
  },
  {
    name: '르와조',
    address: '서울 강서구 공항대로 237 에이스타워 120호',
    sido: '서울특별시',
    gungu: '강서구',
    dong: '마곡동',
    subway: '발산역',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티커피,대회 수상',
    description:
      '르와조는 원두납품을 전문으로 하는 로스터리 카페입니다.\n로스팅룸은 경기도 김포에 위치해 있으며,\n발산점은 쇼룸의 형태로 운영됩니다.\n\n[Brewing List]\nPanama Janson Falcon Geisha\n파나마 잔슨 팔콘 게이샤\nCosta Rica Don Mayo\n코스타리카 돈 마요 시나몬\nEthiopia Bensa Bombe\n에티오피아 벤사 봄베\nPeru Decaffeine\n페루 디카페인\nGuatemala El Socorro\n과테말라 엘 소코로\n\n[Special Espresso]\nColombia Cranberrry 콜롬비아 로꼬시리즈 크랜베리\n\n2019 KBrC 파이널리스트 /\n-브루잉부문 국가대표 바리스타 선발전 수상\n2019 GCA 에스프레소부문 금상 /\n2020 에스프레소 스로우다운 서울 1위 /\n2020 에스프레소 스로우다운 익산3위 /\n2020 에스프레소 스로우다운 파이널 4위 /\n2021 MOC 에스프레소부문 TOP 3 /\n2021 마스터오브카페 1위\n2022 MOC 브루잉부문 금상\n2022 마스터오브카페 3위\n2021-22 에스프레소 스로우다운 파이널 2위\n2022 골든커피어워드 하우스블렌드 부문 장려상\n2022 KBrC 파이널리스트 /\n-브루잉부문 국가대표 바리스타 선발전 수상',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMDA5MjVfNjkg%2FMDAxNjAxMDM2MTA5NTI4.cvHp5Y_n59cXe7lA_PBJhkzWRh1WmAnXy5LGpNWhPUMg.pGS8fnxgNasiLtG07wSqKMfrajejfnVB6lEKD0EIjccg.JPEG.joowon0208%2FDSCF4424.jpg',
    'images.1':
      'https://ldb-phinf.pstatic.net/20210701_196/1625129129379p6cWg_JPEG/Ejoswn54DvmT4b5jsZF28aaX.jpg',
  },
  {
    name: '고로커피로스터스',
    address: '서울 관악구 남부순환로231길 33',
    sido: '서울특별시',
    gungu: '관악구',
    dong: '봉천동',
    subway: '서울대입구역',
    description:
      '고로커피로스터스는 봉천동 한적한 골목안에 위치한 작은카페입니다.\n스쳐가는 사람들로 가득한 매장이기 보다는 안부를 묻고 소소한 이야기를 나눌 수 있는 공간이길 원합니다.\n그 안에서 정성을 다한 커피와 디저트가 조금이나마 온기를 더해줄 수 있기를 기원합니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200528_110%2F1590672571274vBuQW_JPEG%2FrnMpJ3dSLv6Su5NxZyvc2OW5.jpeg.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200505_251%2F1588680732469g6Ij8_JPEG%2FTmzLD1oImyak0P7o3uHEljOD.jpeg.jpg',
  },
  {
    name: '아이딜',
    address: '서울 관악구 행운길 7 1층 아이딜 카페',
    sido: '서울특별시',
    gungu: '관악구',
    dong: '봉천동',
    subway: '낙성대역',
    wifi: 'O',
    pet: 'O',
    tags: '디저트',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA0MjlfMTI1%2FMDAxNjUxMjA5NDA5Mzkw.Enw4PqS73LyNfq3tpH1mTz2uR-RYPSIyLKU_oR8lwp0g.h4yvXhzsVGPaB32iHsik_MJZ_1xNIzCA_52lYeAhk64g.JPEG.luckyroadone%2FDSC08113-3.jpg',
    'images.1':
      'https://ldb-phinf.pstatic.net/20210120_208/1611123953747qftJQ_JPEG/A0RiG2AEqUbJ74VyOe6_c3-t.jpeg.jpg',
  },
  {
    name: '로프커피',
    address: '서울 광진구 동일로 304 1층 로프커피',
    sido: '서울특별시',
    gungu: '광진구',
    dong: '군자동 ',
    subway: '군자역 ',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '라떼아트',
    description:
      '"Hello+한국 라떼아트 챔피언이 직접 로스팅하고 매장을 운영하고 있습니다^^!!\n맛있는 커피 유니크한 인테리어 카페 핫 플레이스를 찾고 계시다면\n여기입니다!!!!!"',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA3MjNfNjkg%2FMDAxNjI3MDIzNDUzODU2.UItCf3V3LJ86x5WkDEJUy9iXUVn2eMS9d9xw7cymh_Ag.02QSST42wByKMTYbOEcHVzxf6b3Q9ujEXd170Ny0TZAg.JPEG.zs2oo%2FIMG_7508.JPG',
    'images.1':
      'https://ldb-phinf.pstatic.net/20220213_32/1644737887446LP3b1_JPEG/KakaoTalk_20220213_161926238_01.jpg?type=f459_345_60_sharpen',
  },
  {
    name: '카페원웨이',
    address: '서울 광진구 천호대로119길 58 1층 카페원웨이',
    sido: '서울특별시',
    gungu: '광진구',
    dong: '중곡동',
    subway: '군자역',
    wifi: 'O',
    parking: 'O',
    tags: '라떼아트',
    description:
      '안녕하세요^^ 2012년에 오픈한 카페원웨이는 라떼아트 챔피언이 운영하는 카페입니다',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2F20150604_101%2Fdreamer_hsb_14333510122472bXix_JPEG%2F20150603_181946_385.jpg',
    'images.1':
      'https://ldb-phinf.pstatic.net/20200513_234/1589376877467SH75q_JPEG/ZmH5WgAIIVtQ1DrPdUa6ffyu.jpg',
  },
  {
    name: '보난자커피 군자점',
    address: '서울 광진구 능동로 239-1 B동 1층 보난자 커피',
    sido: '서울특별시',
    gungu: '광진구',
    dong: '군자동',
    subway: '어린이대공원역',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    description:
      '(Unnecessarily Good) Bonanza Coffee\n\n필요 이상의 집착, 끝없는 궁금증.\n혹자는 우리가 너무 과하다 말할지도 모른다. 그러나 그것이 우리가 꿈꾸는 것이다.\n커피라는 이름으로 남들이 가지 않았던 그 먼 곳으로 가보는 것.\n\n한때 베를린에서 스페셜티 등급의 좋은 커피를 찾을 수 없었다는 걸 알고 있는가?\n하지만 지난 몇 년간 커피에 목숨을 바친 사람들이 베를린을 제3의 물결, 스페셜티 커피의 천국으로 바꿔놓았다. 2006년 Unnecessarily Good 필요 이상의 집착을 외치며 등장한 보난자커피가 그 물결의 시작이었다. 아프리카의 아주 작은 농장에서부터 인도네시아, 남미까지 더 나은 한 잔의 커피를 만들기 위해서라면 어디든 찾아갔던 보난자커피는 세계의 많은 매체들로부터 당신이 죽기 전에 반드시 가봐야 할 세계 25대 카페, 유럽을 대표하는 5대 카페, 2021 세계 최고의 10대 카페로 선정되었다.\n\n보난자커피는 현재 베를린에 세 곳의 매장과 로스팅 공간을 가지고 있으며, 네 번째 매장을 준비하고 있다. 유럽 전역의 많은 카페와 다이닝에 원두를 공급하고 있으며, 국내에서는 2016년부터 mtl을 통해 한국 소비자들을 만난다. 2022년 5월, 한국을 거점으로 아시아 시장 진출을 준비하고 있는 보난자커피는 두 개의 매장을 선보였다. 군자점에는 로스터리와 카페, 키친까지 겸비한 플래그쉽 매장을, 롯데백화점 명동점에는 쇼룸 형태의 매장을 열었다.\n\n이들의 행보가 궁금하다면,\n\n@bonanzacoffee @bonanzacoffee_korea',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220518_282%2F1652862362691gyy2f_PNG%2F%25BD%25BA%25C5%25A9%25B8%25B0%25BC%25A6_2022-05-18_%25BF%25C0%25C8%25C4_5.20.43.png',
    'images.1':
      'https://ldb-phinf.pstatic.net/20220622_161/16558794048334TyFs_JPEG/%28%C7%CA%C5%CD%C4%BF%C7%C7%29Sasaba_ethiopia2.jpg?type=f459_345_60_sharpen',
  },
  {
    name: '빈브라더스 현대백화점 디큐브시티점',
    address: '서울 구로구 경인로 662 현대백화점 별관 3층',
    sido: '서울특별시',
    gungu: '구로구',
    dong: '신도림동',
    subway: '신도림역',
    wifi: 'O',
    parking: 'O',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMDA1MzFfMTkx%2FMDAxNTkwODU2MjQzODI3.9bsSrukW4r-io6e-YzvkLUHKXru2AGcpf8WLBAflcP0g.EaTNUY1_uX02YTtIS57azMHMlCGfkPrHptaBqN4Hw6Yg.JPEG.romilywork%2FKakaoTalk_20200529_175200980_%25281%2529.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200415_143%2F15869154238886L73c_JPEG%2F5EpULsDXJFf0ItiIyQTR6dGf.jpg',
  },
  {
    name: '무이커피랩',
    address: '서울 구로구 디지털로31길 38-9 602호',
    sido: '서울특별시',
    gungu: '구로구',
    dong: '구로동',
    subway: '남구로역',
    parking: 'O',
    tags: '로스터리,스페셜티커피,카페창업컨설팅',
    description:
      '무이커피랩은 프로 로스팅 테크닉 부터 브랜드 디자인까지 카페 창업의 All in one system을 제공합니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20211109_195%2F1636435793951HNhny_PNG%2FzRwyupt1AWsq4yE9MXRJr707.png',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20211109_147%2F1636435867737luDSM_JPEG%2FTRWY3eXKK6Qxf7OHr2Kr7nn1.jpeg.jpg',
  },
  {
    name: '이미 커피 로스터스',
    address: '서울 구로구 디지털로27길 116',
    sido: '서울특별시',
    gungu: '구로구',
    dong: '구로동',
    subway: '남구로역',
    wifi: 'O',
    description:
      '* 카페 영업은 하지 않습니다.\n\n이미커피로스터스는\n매일 마셔도 친숙한 커피부터\n특별한 경험과 즐거움을 주는 커피까지\n직접 생두를 선별하고 로스팅하는\n이미커피의 로스팅룸입니다.\n\n원두구매는 네이버 스마트 스토어에서 하실 수 있습니다.\nhttps://smartstore.naver.com/imicoffee\n\n카카오톡에서 이미커피 로스터스 채널을 추가하시면\n납품에 대한 상담과 안내를 받으실 수 있습니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20190328_185%2F1553760849824DxPJW_JPEG%2F1T6WlIqxzvHz8lFk3VGCVXSj.jpg',
    'images.1':
      'https://ldb-phinf.pstatic.net/20200704_35/1593837144473Aok0G_JPEG/gFBt9wuDCYI6KDp61JYWYapT.jpeg.jpg',
  },
  {
    name: '블루마일스커피로스터즈',
    address: '서울 노원구 동일로190길 65 2층',
    sido: '서울특별시',
    gungu: '노원구',
    dong: '공릉동',
    subway: '공릉역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티커피,대회 수상?',
    description:
      '블루마일스는 올바른 커피와 사계절을 느낄 수 있는 디저트로 매일매일의 일상에 새로움과 편안함을 동시에 제공하는 것을 목표로 하는 로스터리&디저트카페입니다.\n\n커피전문가가 직접 엄격한 기준을 통해 생두를 선별하고 재료에 따른 최적화된 로스팅으로 뻔하지 않은 다양한 매력의 커피를 소개합니다.\n\n뉴질랜드, 프랑스산 고메버터, 벨기에 초콜릿, 신선하게 로스팅한 견과류와 제철재료를 통해 수준 높은 디저트를 선보입니다.\n봄, 여름, 가을, 겨울 제철에만 맛볼 수 있는 재료들을 통해 커피와 가장 잘어울리는 시즌 한정 메뉴들을 자체 개발하고 있습니다.\n\n매일 와도 좋은 카페, 혼자 와도, 친구, 가족, 연인 누구와 와도 즐길 수 있는 카페를 만들기 위해 편안한 분위기, 한결같은 맛, 시즌마다 새로운 메뉴를 제공하기 위해 노력합니다.\n\n2층에 위치하고 창문을 전면 개방하여 경춘선 숲길의 풍경을 한 눈에 내려다 볼 수 있는 점 또한 장점입니다.\n\n커피와 매장소식(@bluemilescoffee)과 디저트 라인업(@bluemiles_c00kie)은 각각 인스타를 팔로우하시면 최신 정보를 빠르게 접하실 수 있습니다',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjBfMTgy%2FMDAxNjY2MjIwMjY0MDA5.e-U1aq2u6Bu54ReDOISBrKClkz1BuPxOpULzAp98dqog.OUg1Ih3oASynL9US6vvFOA7oo0R6ZFfrqKc_H4-eyKwg.JPEG.angle7211%2FIMG_5308.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210723_229%2F16270340589589OGcR_JPEG%2FZVGm2vx_NcCIaI3C80JVYhc7.jpeg.jpg',
  },
  {
    name: '슈퍼 내추럴',
    address: '서울 동대문구 전농로23길 78',
    sido: '서울특별시',
    gungu: '동대문구',
    dong: '전농동',
    subway: '청량리역',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티커피',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220310_123%2F16469007457497ES5Y_JPEG%2F26579CE7-035B-4C37-B58F-23638F5BC302.jpeg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20230105_73%2F16728967680917OJoD_JPEG%2F6CF606EE-5350-46F8-82E2-BF241B6B0B75.jpeg',
  },
  {
    name: '커피리브레 연남점',
    address: '서울 마포구 성미산로 200',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '연남동',
    subway: '홍대입구역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티커피',
    description: '다양한 산지의 커피를 합리적인 가격으로 선보입니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20211009_78%2F1633785664286GcR8V_JPEG%2FSDGJWo5A8jvnr_sSfwsLOfnL.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20211008_8%2F1633699939879FQF73_JPEG%2Fbs3nWXFItr1uhzs6owQzIJZN.jpg',
  },
  {
    name: '올웨이즈어거스트 제작소',
    address: '서울 마포구 연남로 71 1층 올웨이즈어거스트',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '연남동',
    subway: '가좌역',
    wifi: 'O',
    tags: '로스터리,스페셜티커피',
    description:
      '자체 로스팅한 원두를 제공합니다. 약간의 디저트와 간단한 토스트를 함께 곁들일 수 있습니다',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjExMTVfNjUg%2FMDAxNjY4NDY5NTI4Njkz._K0mY0ZH9kxBepWU194fnjzLuztLP3_duxsCO_dpDOsg.at5QsnjEPMb76LqRWgyGCbwuKSewyJp_uDzXES3DyAEg.JPEG.shw119527%2F1668393079661.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMjA5MjJfNjMg%2FMDAxNjYzODQwNzgzMjkx.Z8cq4c3GMEU-yw_exldq37rH6_GMFv_od_Qpgts7uNcg.efaETgIvLhYnllnerBqwqjAp7jxOrYGdLiXH7M4N9Lwg.JPEG%2F3197FA87-834B-4978-9E61-192112569642.jpeg',
  },
  {
    name: '커퍼시티',
    address: '서울 마포구 동교로 48 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '합정동',
    subway: '망원역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티커피',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220630_144%2F16565316835599Cil6_PNG%2F02.png',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA2MjRfODUg%2FMDAxNjI0NTIzOTEyNjY5.HfWdMHmjOX1kyk3emKpui0zX7-y1lNO5A5amLxddUeAg.LysJMyc8Q-eXkdz9fG9b0UPwNo7BQFcLWGmt1gLX0iMg.JPEG.kspring917%2FIMG_4202.jpg',
  },
  {
    name: '빈브라더스 합정',
    address: '서울 마포구 토정로 35-1',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '합정동',
    subway: '합정역',
    wifi: 'O',
    tags: '로스터리,스페셜티커피',
    description:
      '합정에는 늘 빈브라더스가 있습니다.\n\n언제든 오셔서 맛있는 싱글오리진 커피와 홈메이드 베이커리를 즐기세요.\n늘 에너지 넘치는 바리스타팀이 여러분의 커피 가이드가 되어드립니다',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20160726_155%2F1469502303512PLBDt_JPEG%2F176676523522287_0.jpeg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210801_280%2F1627820540942SWf4c_PNG%2F2Vm4N-5iF-EVno9kPtiohb9S.png',
  },
  {
    name: '히트커피로스터스 서교',
    address: '서울 마포구 동교로 146 관양빌딩 1층 카페',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '서교동',
    subway: '홍대입구역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티커피',
    description:
      '- 2020 마스터오브로스터 8위\n- 2019 한국 로스팅 국가대표 선발전 9위\n- 영국 글로벌생두기업 falcon 업무제휴\n- 원두납품 / 원두구매 문의 (kakao : 히트커피)',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20211213_244%2F1639354715571Dsj6g_JPEG%2F77BC9028-8833-4217-B7BF-4C7A0741BEC1.jpeg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210801_147%2F1627814351011sWjKb_JPEG%2FuHr9Q3DlOed8MI1Nfq58Lp9f.jpeg.jpg',
  },
  {
    name: '파스텔커피웍스 본점',
    address: '서울 마포구 독막로2길 38 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '합정동',
    subway: '합정역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티커피',
    description:
      '2011년,\n10평 남짓한 작은 카페로 시작하여\n오직 맛있는 커피와 전문가라는\n두 단어에 집중한 커피전문 회사입니다.\n우리는 전 세계 커피를 테스팅하며,\n섬세한 로스팅 프로파일을 연구합니다.\n\nPASTEL COFFEE WORKS\n원두납품문의 Tel. 02-3141-1229\n\n38, Dongmak-ro 2-gil, Mapo-gu, Seoul, Republic of Korea (04071)',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA3MDZfMTcx%2FMDAxNjU3MDM2ODA2NDY3.21AHwUUDV7GGaF7jmRgNbujUDQBiQIfyXEvX079sGnsg.6PqfZmQObSkB-7XrPPxIoyM5m2YvlHU-VdhyssrU1Jog.JPEG.juone7103%2FKakaoTalk_20220703_220710248.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200522_139%2F1590117856255DA2yS_JPEG%2FnrwLUQsY-s--vNQclDSJAagB.jpg',
  },
  {
    name: '에스프레소바 슈가',
    address: '서울 마포구 토정로 37',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '합정동',
    subway: '합정역',
    tags: '로스터리,스페셜티커피,특별한메뉴,에스프레소바',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210620_64%2F1624180318037xHTiE_JPEG%2Fwh_rjq3n9Zh8pZup9kbVpRtu.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjFfNjgg%2FMDAxNjY2MzI5MTI5MjY1.4KOMyZmxOtoJXxw4eJITHtCbdoTsJfzI5-sRilw_MNwg.Ao5ns3PbFp0c4q68NkdZYgaCKyI_ZpHxdnF1Iani73Ag.JPEG.iilh_%2Foutput_1877936075.jpg',
  },
  {
    name: '시러피하우스',
    address: '서울 마포구 독막로19길 8-17 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '상수동',
    subway: '상수역',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티커피,특별한메뉴,에스프레소바',
    description:
      '클래식한 컨셉의 인테리어와 분위기에서\n시러피하우스만의 독특한 에스프레소 메뉴를 비롯해\n<월드시그니처 배틀 챔피언> 고은미 바리스타의\n다양한 시그니처 메뉴를 맛 볼 수 있습니다.\n\n카페 뿐만 아니라 메뉴 개발 및 수업 공간을 가지고 있어 다양한 클래스가 진행됩니다.\n\n인스타그램 시러피하우스를 검색해 주세요.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA3MDVfMyAg%2FMDAxNjU2OTc3NzAzMDE2.992QS9RGgPSTlymtTFEFftDn-s_zJFuONJC9skXvSUgg.sv4S6ybB9ojiKhGoealJHCqXtStzndlIHHaqMjDIjGEg.JPEG.sojeong1224%2Foutput_1615065626.jpg',
    'images.1':
      'https://ldb-phinf.pstatic.net/20220504_283/1651650175637afeKo_JPEG/%BB%F3%BC%F6%BF%AA_%BD%C5%BB%F3%C4%AB%C6%E4_%BD%C3%B7%AF%C7%C7%C7%CF%BF%EC%BD%BA_%286%29.jpg',
  },
  {
    name: '딥블루레이크',
    address: '서울 마포구 포은로6길 11',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '망원1동',
    subway: '망원역',
    wifi: 'O',
    tags: '로스터리,스페셜티커피,원두구매',
    description:
      '커피를 음식이라고 본다면 재료가 중요하다고 생각합니다. 좋은 재료로 맛있는 커피를 만들기 위해 노력 중입니다.\n재료의 특성을 잘 나타내기 위해 북유럽 스타일의 로스팅',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210716_263%2F1626425692386SFWA7_PNG%2FvnpsdvzsHBGmgWQVwvI2aZ3l.PNG.png',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxNzAzMjlfMjcy%2FMDAxNDkwNzY2NzkxNTY0.VgYLRIt_GOG9pAHnMQ9nnuOwODVE7BzkHAd1dVDio8Mg.PCbQ_GLbHZ0fmOdpo8AcGdzURgkXQGqxMHXze76518Mg.JPEG.pinkrose_95%2F5509D7D0-279D-4A60-981F-2BE7E5CA2B9B.JPG',
  },
  {
    name: '도덕과 규범',
    address: '서울 마포구 독막로28길 34 도덕과 규범',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '신수동',
    subway: '광흥창역',
    tags: '로스터리,스페셜티커피,원두구매',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220915_74%2F1663230858125xxWDr_JPEG%2F0BAD9E37-E1C7-46E3-BC3F-34646A3391C1.jpeg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220310_159%2F16469041247952qvEU_JPEG%2F%25B7%25CE%25B0%25ED.jpeg',
  },
  {
    name: '후엘고',
    address: '서울 마포구 마포대로11길 118',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '염리동',
    subway: '공덕역',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티커피,원두구매',
    description:
      '주말 및 공휴일 노트북 사용을 제한합니다. 방문 하시는 모든분들의 편의를 위하여 양해 부탁드립니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA4MDNfMjIy%2FMDAxNjU5NDk4NDUyNzIx.CtNmsqMlX3uYikJVyA_ePBA5qgJKcSjahB0G_zxxNOAg.AGx9-7heLOo4fxf04z5iLDVAtXDf2s_5BxdpnWB0naAg.JPEG.aintnuttin%2FIMG_7376.JPG',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20180531_175%2F15277448500303LiWE_JPEG%2Fh2M_zuozCmDOonSTE-eNkgNV.jpg',
  },
  {
    name: '몬스터케이브',
    address: '서울 마포구 신촌로4길 22-8 101호',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '동교동',
    subway: '홍대입구역',
    wifi: 'O',
    pet: 'O',
    tags: '특별한메뉴',
    description:
      '주인취향의 커피,음료,알콜,베이커리,음악,공간 을 함께 즐기는 리얼 커피바.\n가내수공업 수제의 길을 걷는 차기 커피장인의 공간으로 놀러오세요 :)',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20191016_185%2F1571231888984nMchM_JPEG%2FeTBDNawRthQKUxDOXfYJZiWP.jpeg.jpg',
    'images.1':
      'https://mblogthumb-phinf.pstatic.net/MjAxNzEyMDRfMjcy/MDAxNTEyMzk4MDkzNTk2.dqBxM5xQXUJB0-jQMde48lb6956WaueNOZpbU0vep9Ag.bjKTjggwAAU-1SzI26QURB6MN67EpMNBu3gbq5KclsUg.JPEG.snowa12/IMG_2645.JPG?type=w2',
  },
  {
    name: '프릳츠 도화점',
    address: '서울 마포구 새창로2길 17',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '도화동',
    subway: '마포역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티커피',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20180518_213%2F15266155090043BJKb_JPEG%2FyDTNCS3DtFGlKz_Bc9ZxbxLQ.JPG.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220922_160%2F1663825513836iidni_JPEG%2F%25B7%25D5%25BA%25ED%25B7%25A2.jpg',
  },
  {
    name: '립하버(Liebhaber)',
    address: '서울 마포구 백범로24길 11-4 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '염리동',
    subway: '대흥역',
    wifi: 'O',
    pet: 'O',
    tags: '디저트,독일',
    description:
      '진짜 독일인이 만드는 독일식 치즈와 치즈케이크, 호밀빵을 맛볼 수 있어요!\n\n독일인이신 사장님이 혼자 직접 만드는 치즈에는 칼슘, 프로틴, 비타민B 등 영양이 풍부하게 들어가 있고 설탕+방부제는 들어가지 않아, 운동이나 채식하시는 분들이 드시기에도 좋아요.\n또한 기본 치즈에 허브, 파프리카, 과일 등 여러가지 재료를 섞어 더 다양한 종류의 치즈를 즐기실 수 있어요.\n\n치즈케이크는 매일 다른 종류를 구워, 오늘의 치즈케이크를 골라먹는 재미도 있어요.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20180910_140%2F1536564283992s8zWx_JPEG%2FsB6LnkW1ScslaUGAW9xbMd8f.jpeg.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220219_170%2F1645254813386qizcY_JPEG%2F62809CB0-FD72-4FB5-8CA7-BF739508B1FD.jpeg',
  },
  {
    name: '커피하우스마이샤',
    address: '서울 마포구 포은로 52 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '합정동',
    subway: '망원역',
    tags: '로스터리,스페셜티커피,강배전,석탄단',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA4MjlfMTU3%2FMDAxNjYxNzY4NTg3NzU3.Cp42bnbmWSD7GlOSq2tVpiJjsMEOZlKkIlSgjzL1uI0g.xYr32djw-YBxd87d_dIujsY8SQa8MXq8ykkqcbKY2Rkg.JPEG.rnjsxodnd321%2F1661676675194.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200607_118%2F15915352205232TW15_JPEG%2FOe026SdTPqUkMYA2iK6gsUtU.jpg',
  },
  {
    name: '이젤커피앤바',
    address: '서울 마포구 희우정로20길 22-12 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '망원동',
    subway: '망원역',
    wifi: 'O',
    pet: 'O',
    tags: '와인바',
    description:
      '파스타와 와인 모카포트로 만든 에스프레소를 소개합니다.\n빵도 굽고 예술서적도 판매합니다.\n\n12/6 ~ 13 겨울휴가 기간입니다.\n방문에 참고 부탁드립니다.\n\n감사합니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220225_134%2F1645775557879MbagM_JPEG%2FIMG_6273.JPG',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220217_44%2F1645104240500hHwkE_JPEG%2FKakaoTalk_Photo_2022-02-17-22-23-02_002.jpeg',
  },
  {
    name: '올웨이즈어거스트로스터스',
    address: '서울 마포구 망원로6길 19 1층 일부',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '망원동',
    subway: '망원역',
    tags: '로스터리,스페셜티커피,스웨덴',
    description:
      '전화통화 연결이 어려울 수 있습니다. 매장 sns로 연락 부탁드립니다.\n\n스웨덴 스페셜티 Drop coffee로 브루잉, 에스프레소는 자체 블랜딩과 Drop coffee 두가지 운영중입니다.\n매장 내부는 저희가 직접 디자인한 제품 또는 빈티지, 해외 직접 수입한 제품들로 꾸며져 있습니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210308_108%2F16151596319920T3gp_JPEG%2FyzjVfDMoK0Qmc5VNc2G1jRHS.jpeg.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMzAxMDlfMjg4%2FMDAxNjczMjUxMzQyNDM0.HbfzwSgb7PCbhPNu3HOVuxNQKqH1MAzVunKqBiHmPIQg.dO_lSnMuwlZBGLiEM7GIOARnrPs8RQpBQ6gN--lRCWog.JPEG%2FF5183414-4D2E-4118-8092-6A0407036584.jpeg',
  },
  {
    name: '코페아신드롬 마포점',
    address: '서울 마포구 새터산길 1 지층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '성산동',
    subway: '마포구청역',
    tags: '로스터리,스페셜티커피,원두구매',
    description:
      '코페아신드롬은 마스터 김나영이 2017년 일본 귀국이후 인천에서 오픈한 로스터리 빈즈숍을 시작으로 2021년4월24일에 마포점을 오픈했습니다.\n마스터 김나영은 "커피대전"의 저자이며 "카페바흐"의 창업자인 커피거장 다구찌마모루가 아끼는 애제자로서 커피로스팅을 전수받았습니다. 한편, 커피의 다른 분야로서 강배전 융드립을 다이보커피점의 마스터였던 다이보카츠지 마스터로부터 사사했습니다.\n\n코페아신드롬 마포점은 로스팅레벨에 따라 순차적으로 변화하는 30종류의 원두들을 이용해서 핸드드립, 융드립, 사이폰, 점드립, 에스프레소 음료를 제공합니다.\n\n요즘 유행하는 스페셜티커피의 후루티한 산미부터 허브와 스파이스한 커피맛의 강배전까지 커피가 가지고 있는 다양성을 각각의 커피추출법을 통해 폭넓게 경험하실 수 있습니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA2MDJfMTk1%2FMDAxNjIyNjA3NzI2NDk3.L7RiO5ONVoaY8If4U87xEm7WqwTeUS6sZnsJlFT01Gkg.std6YYNM-3X3tbBlR4vPzWk065RiikJ8ktgs_69e1Twg.JPEG.kgskgs1108%2FKakaoTalk_20210602_090144445_05.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210419_291%2F16188429818093ffyl_JPEG%2FTTec0Y_gydD22bhrlBJ9YzWi.jpg',
  },
  {
    name: '서교동 그 카페',
    address: '서울 마포구 동교로19길 66 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '서교동',
    subway: '망원역',
    tags: '로스터리,스페셜티커피,가성비',
    description:
      '다양한 스페셜티 커피를 최대한 저렴한 가격에 드리도록 노력하는 스몰 로스터리 카페입니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210517_130%2F16212386661026uEOP_JPEG%2FzER80iC0H5IBwHGxbsbKO_ZP.jpeg.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210525_212%2F162191206096859ACU_JPEG%2FP20b1UVoXQPuqOPEJOpZB_Ns.jpeg.jpg',
  },
  {
    name: '충무공 커피바',
    address: '서울 마포구 동교로 181-6 1층',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '동교동',
    subway: '홍대입구역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티커피',
    description: '로스터리 충무공 커피바입니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjExMDlfMjM2%2FMDAxNjY3OTgyMjg2ODEz.kQgqEUO1BVMyZDiHSQYaDQffG5HEDOGIVdl_FEDkb6Ug.-qLnUYFfJ_6vLWOzONRqFpQxakx93_BpoM_I0U_dxpcg.JPEG.aivsrur%2FKakaoTalk_20221014_014946198.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220623_204%2F1655968136162UqM8P_JPEG%2FKakaoTalk_20220623_160452331_01.jpg',
  },
  {
    name: '카페 바우',
    address: '서울 마포구 와우산로29라길 7',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '서교동',
    subway: '홍대입구역',
    wifi: 'O',
    tags: '로스터리,스페셜티커피,밀크티,영국',
    description:
      '냉침밀크티와 더치커피가 맛있는 리얼앤틱카페/\n\n35년경력의 청와대출신 커피마스터가 직접 제조하는 특허등록 와인더치.위스키더치.샴페인밀크티가 유명한 홍대앤틱카페/\n\n40여종의 더치커피와 밀크티.그외 각종 티.에스프레소가 준비되어있고. 200년이상된 앤틱찻잔을 직접 골라 고가구 테이블.의자에서 티타임을 가질 수 있습니다.(카페안의 가구들은 200여년이상된 중세유럽가구들입니다).',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20181219_45%2F1545203309442bx1H5_JPEG%2FYhi2ZJb39LRl2CIq7wP6EbsR.JPG.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20181219_267%2F1545203315679AAApy_JPEG%2FRy5WI64QtqJbfVxBQbbzbc1w.JPG.jpg',
  },
  {
    name: '8810 리스트레토 바',
    address: '서울 마포구 월드컵북로6길 88-10',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '동교동',
    subway: '홍대입구역',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티커피',
    description:
      '스페셜티 100% 블렌딩 만을 사용하여 전문 바리스타들이 최고의 커피만을 추구합니다.\n\n라마르조꼬 레바X 국내 첫런칭 매장으로서 하이엔드급 머신 및 기기를 자랑합니다\n물론 리스트레토 스킬 및 머신 테크닉,메카니즘 에 대하여 끊이없이 노력합니다.\n\n맛을 위해서라면 어떤 재료든 사용하며 아끼지 않습니다.\n\n음료 한잔의 퀄리티는 가히 최고 수준입니다.\n\n스페셜티 커피 전문\n연남동 주차가능 카페',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20190701_278%2F1561950058454nlVHA_JPEG%2FRURkF-xT4f1GA65eiBIVj2C2.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20190701_61%2F15619500585586qhwk_JPEG%2F_QZkNtFhMHqF-uBxtecFiCNQ.jpg',
  },
  {
    name: '펠른',
    address: "서울 마포구 성미산로22길 18 A'동 1층 펠른",
    sido: '서울특별시',
    gungu: '마포구',
    dong: '연남동',
    subway: '홍대입구역',
    wifi: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티,특별한메뉴,디저트,블루리본',
    description:
      '단순 커피를 넘어 고객이 원하는 맛과 향을 선택할 수 있는 커피 페어링 코스를 통해 다양한 커피를 느껴보세요.\n이제 펠른에서 커피 페어링 코스를 경험해보시기 바랍니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220730_125%2F1659163416201uBaqM_JPEG%2FcwKO1PtNad5AFaiYf_VNm_xW.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220730_51%2F1659163412833YDuh4_JPEG%2FAT_Perlen_Spaces11_%25BF%25EB%25B7%25AE%25C1%25D9%25C0%25D3.jpg',
  },
  {
    name: '리틀프레스커피',
    address: '서울 마포구 성미산로 198 리틀프레스커피',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '연남동',
    subway: '홍대입구역',
    tags: '로스터리,스페셜티,이탈리아',
    description:
      '연남동 리틀프레스커피는 모카포트가 있는 집으로 운영 되고 있습니다.\n신선한 원두와 드립백을 판매하고 있으며 런치 파스타와 스페셜티로 내린 모카포트커피를 제공하고 있습니다.\n모카포트가 있는 집에서 작은 이태리를 경험해 보세요.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20190612_90%2F1560331447532iAUoi_JPEG%2FKw4ET9g9Ela7t1_8vNDYX2pg.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200703_250%2F1593771502465enhMl_JPEG%2F7yXkenNEs0y1qvVhG4maDur0.jpg',
  },
  {
    name: '타셋커피 로스터스',
    address: '서울 마포구 월드컵북로 396 누리꿈스퀘어 B1108호',
    sido: '서울특별시',
    gungu: '마포구',
    dong: '상암동',
    subway: '수색역',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티',
    description:
      "상암 누리꿈스퀘어 '로스터리카페' 타셋커피입니다 :)\n스페셜티커피 / 디카페인커피 / 핸드드립 / 콜드브루 / 원두도소매 / 휘낭시에 / 르뱅쿠키 맛.집.'ㅅ' !!!\n오늘도 수고한 당신에게 :)",
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220602_127%2F1654158152015Rffci_JPEG%2FKakaoTalk_20220506_140125047.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220602_181%2F1654158182182JTV1P_JPEG%2FKakaoTalk_20220506_140125047_03.jpg',
  },
  {
    name: '디폴트밸류',
    address: '서울 서대문구 성산로 333 1층',
    sido: '서울특별시',
    gungu: '서대문구',
    dong: '연희동',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티',
    description:
      '디폴트밸류는 정기적으로 바리스타들이 애정하는 음료 3가지를 선정하고 그에 어울리는 디저트를 오마카세로 제공하고 있습니다',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA5MjNfMjU5%2FMDAxNjYzODk5Njg0OTAy.8lf1HcNPO60dOLkfwRxRFFTXbdBDMCqisNE5Qx74P_0g.mT_iFJ-hKiHC3PgxtOf65mtcZSyKQRfqVUfFV2kaJwcg.JPEG.mistakeni%2FIMG_2528.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210912_111%2F1631423396665RLqCh_JPEG%2Fimage.jpg',
  },
  {
    name: '더니커피',
    address: '서울 서대문구 연희로11길 41 1층',
    sido: '서울특별시',
    gungu: '서대문구',
    dong: '연희동',
    tags: '로스터리,스페셜티,원두구매',
    description:
      '매주 다양한 스페셜티 커피를 소개하는 마이크로 로스터리 커피숍',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20181215_223%2F1544837462916YqNY6_JPEG%2FkAvcU7FOnWOat8ewLN2EMnzy.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMDA4MDNfMjEw%2FMDAxNTk2NDQ0MzY5Nzk0.sdoZHALfX7NnWoa_nrz148mlW0LJ-0jSul7RoVCeHMcg.7mKJ06guMjTWcn-IqMP2Rhp4KvadzYLpMs9OmT_3eAog.JPEG.y2kpjy7716%2FIMG_1470.jpg',
  },
  {
    name: '아이덴티티커피랩',
    address: '서울 서대문구 모래내로 390',
    sido: '서울특별시',
    gungu: '서대문구',
    dong: '연희동',
    subway: '홍제역',
    tags: '로스터리,스페셜티,원두구매',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjAzMDlfNTcg%2FMDAxNjQ2ODI4NTY3MzE5.eLfoCWpY7-ziDdVx9ZsheEu-8UFT4v2NP7Ouy4OhDs8g.ckiDc7kNRXvEdaz7ia2ysfGo1WwHzaHMpPSEaT6gfaQg.JPEG.jjooo823%2Foutput_3433239587.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210520_113%2F1621503125128xDbeL_JPEG%2FcmmSDAhRrOvKlFZ-b7RDfezs.jpeg.jpg',
  },
  {
    name: '컬러드 빈(Coloured Bean)',
    address: '서울 서대문구 연희로11가길 8-8',
    sido: '서울특별시',
    gungu: '서대문구',
    dong: '연희동',
    subway: '홍대입구역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티,호주',
    description:
      '호주에서 오랜기간 근무 후 돌아온 바리스타가 커피를 내려드리는 연희동 컬러드 빈 입니다. 다양한 우유 커피를 기본으로 깨끗하고 다채로운 필터커피도 동시에 제공합니다. (디카페인 및 논커피 메뉴도 동시에 준비되어있습니다.)',
    'images.0':
      'https://ldb-phinf.pstatic.net/20230105_13/16729224314392C4Lt_JPEG/KakaoTalk_Photo_2022-07-12-19-04-10_006.jpeg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20230105_217%2F1672922432177aPqfU_JPEG%2FKakaoTalk_Photo_2022-07-12-19-04-28_005.jpeg',
  },
  {
    name: '니도 로스터리',
    address: '서울 서대문구 연희로 190 102호',
    sido: '서울특별시',
    gungu: '서대문구',
    dong: '연희동',
    wifi: 'O',
    pet: 'O',
    parking: 'O',
    tags: '로스터리,스페셜티,원두판매',
    description:
      '도심속 작은 테라리움에서 즐기는 스페셜티 커피 Nido (Italia) : 둥지 Roastery (English) : 커피를 볶아 파는 장소',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220723_167%2F16585491704516nUvq_JPEG%2F%25C1%25A4%25B8%25E9jpg.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220502_194%2F1651479384381WKOFA_GIF%2F%25B4%25CF%25B5%25B5%25BB%25E7%25C1%25F82.gif',
  },
  {
    name: '룰커피',
    address: '서울 서초구 반포대로7길 16 청목빌딩 1층',
    sido: '서울특별시',
    gungu: '서초구',
    dong: '서초동',
    subway: '남부터미널역',
    pet: 'O',
    tags: '로스터리,스페셜티,원두판매',
    description:
      '룰커피(LULL) LOVE YOU All 줄임말로 모두 사랑하며 행복하길 바라는 마음으로 만든 모던 카페입니다,\n\n서초동 예술의전당, 악기거리에 위치한 룰커피는 정인성 바리스타가 직접 로스팅하고 정성스럽게 커피를 내리며, 위트있게 이끌어 나가는 공간입니다,\n\n커피와 함께 소소하게 즐길 수 있는 디저트는 매일 아침 직접 반죽하여 구워내고 있습니다.',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA0MDNfMSAg%2FMDAxNjQ4OTc1MjgxMTE2.TdAKHqiK3PtkIYY_5fVMxXWGaX80LqpJOOY_WgVLfz8g.pB5XmBI4i-XoqbJgpbFoDBvHIKrxi-1baFbpmQfGSdAg.JPEG.kmj35377%2F1648543582748%25A3%25AD1.jpg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=f320_320&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20220827_252%2F16616032394549JISv_JPEG%2FE3C60357-B34F-4B4C-BD87-FD931C0615C2.jpeg',
  },
  {
    name: '파이브브루잉',
    address: '서울 서초구 서초대로27길 15',
    sido: '서울특별시',
    gungu: '서초구',
    dong: '방배동',
    subway: '내방역',
    pet: 'O',
    tags: '로스터리,스페셜티,원두판매',
    description:
      '파이브브루잉 카페는 2012년 국내 최초 브루잉 커피를 이바지한 헤리티지를 담아 차별화된 공간으로 스토리를 만들어 우리가 지향하는 커피의 가치를 높이며 소개하고 있습니다. 만드는 사람의 감성이 반영되는 커피의 매력을 전하고자 하는 도형수 바리스타의 커피, 이제 직접 만나보세요.\n\n파이브브루잉 주식회사는 다양한 브랜드와 협업하며 원두 유통 및 OEM원두 QC에도 참여하고 있습니다. 만드는 사람의 감성이 반영되는 커피의 매력을 전하고자 하는 도형수 바리스타의 커피, 이제 직접 만나보세요.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMjA1MjFfMjg3%2FMDAxNjUzMTI3ODg3MDE1.8nUPrZaA6FiYUlwGvoUZnQceyA43q4qdfBfeW9LwxAYg.RJsyYAClWzqz88F6e1dMmiLC3InnKW1FKtwmJE6vQ2Ig.JPEG%2Fupload_ac81cc87f4e0b9b5945269b2fbf20fce.jpeg',
    'images.1':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fpup-review-phinf.pstatic.net%2FMjAyMjA5MDRfMTk2%2FMDAxNjYyMjc3ODY1NzA4.gG84vl9sp7Iv7uzG5GqMnq6FpxbyTFvrSnjMkkGpfw8g.LDY5zlKPWIoZCZlLpErbNnNnKttsaqS87QwiVdc9MTIg.JPEG%2F1B5E3C2C-8DF7-47D2-B61E-E6F2C4DA6F55.jpeg',
  },
  {
    name: '프릳츠 양재점',
    address: '서울 서초구 강남대로37길 24-11',
    sido: '서울특별시',
    gungu: '서초구',
    dong: '서초동',
    subway: '양재역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '피어커피',
    address: '서울 성동구 광나루로4가길 24 1층 피어커피',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동2가',
    subway: '성수역',
    wifi: 'O',
  },
  {
    name: '로우키',
    address: '서울 성동구 연무장3길 6 1층, B1층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동2가',
    subway: '성수역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리',
  },
  {
    name: '윈야드 성수',
    address: '서울 성동구 연무장길 8-1',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '뚝섬역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '카모플라쥬(camouflage coffee)',
    address: '서울 성동구 아차산로1길 9',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '뚝섬역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리',
  },
  {
    name: '더반 베를린 성수점',
    address: '서울 성동구 뚝섬로17길 31-22 더반 베를린 코리아 성수',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동2가',
    subway: '성수역',
    wifi: 'O',
  },
  {
    name: '메쉬커피',
    address: '서울 성동구 서울숲길 43',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '뚝섬역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '기미사 성수',
    address: '서울 성동구 성수이로26길 47 1층, 지하1층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동2가',
    subway: '성수역',
    wifi: 'O',
  },
  {
    name: '브루잉 세레모니',
    address: '서울 성동구 연무장5가길 22-1 1층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동2가',
    subway: '성수역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '로우키',
    address: '서울 성동구 뚝섬로1나길 5 1층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '뚝섬역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '에디션덴마크 서울숲 쇼룸',
    address: '서울 성동구 성수일로 1 1층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '서울숲역',
  },
  {
    name: '목로정원',
    address: '서울 성동구 서울숲2길 47 3층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '서울숲역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '센터커피 서울숲점',
    address: '서울 성동구 서울숲2길 28-11',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '서울숲역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리',
  },
  {
    name: '콜렉트',
    address: '서울 성동구 서울숲2길 20-8 1층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '서울숲역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '리커버리커피바',
    address: '서울 성동구 왕십리로16가길 10 1층',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '성수동1가',
    subway: '뚝섬역',
  },
  {
    name: '오버나잇 커피 로스터스',
    address: '서울 성동구 왕십리로 410 J동 B106-1호',
    sido: '서울특별시',
    gungu: '성동구',
    dong: '하왕십리동',
    subway: '상왕십리역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '리이케커피',
    address: '서울 성북구 보문로34가길 24',
    sido: '서울특별시',
    gungu: '성북구',
    dong: '동선동3가',
    subway: '성신여대입구역',
  },
  {
    name: '하우스서울',
    address: '서울 송파구 백제고분로9길 5',
    sido: '서울특별시',
    gungu: '송파구',
    dong: '잠실동',
    subway: '종합운동장역',
    wifi: 'O',
  },
  {
    name: '뷰클런즈',
    address: '서울 송파구 백제고분로43길 10 1층',
    sido: '서울특별시',
    gungu: '송파구',
    dong: '송파동',
    subway: '송파나루역',
    wifi: 'O',
  },
  {
    name: '선호 커피 로스터스',
    address: '서울 송파구 송이로2길 4 1층',
    sido: '서울특별시',
    gungu: '송파구',
    dong: '송파동',
    subway: '송파역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '썸띵에스프레소',
    address: '썸띵에스프레소',
    sido: '서울특별시',
    gungu: '송파구',
    dong: '오금동',
    subway: '방이역',
  },
  {
    name: '쟈코피즈',
    address: '서울 송파구 양재대로 1222 올림픽프라자상가 1층 197호',
    sido: '서울특별시',
    gungu: '송파구',
    dong: '방이동',
    subway: '올림픽공원역',
  },
  {
    name: '유어홈 커피로스터스',
    address: '서울 영등포구 도림로133길 20 1층',
    sido: '서울특별시',
    gungu: '영등포구',
    dong: '문래동2가',
    subway: '문래역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '바마셀',
    address: '서울 용산구 원효로89길 12 건물뒷편 1층',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '원효로1가',
    subway: '남영역',
  },
  {
    name: '트레버틴',
    address: '서울 용산구 한강대로7길 18-7',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '한강로3가',
    wifi: 'O',
  },
  {
    name: '센터커피 서울역점',
    address: '서울 용산구 한강대로 405 4층',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '동자동',
    subway: '서울역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '엘카페커피로스터스',
    address: '서울 용산구 후암로 68 B1',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '후암동',
    subway: '서울역',
    wifi: 'O',
  },
  {
    name: '노리밋커피바',
    address: '서울 용산구 후암로35길 51 1층',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '후암동',
    subway: '서울역',
    pet: 'O',
  },
  {
    name: 'mtl 효창',
    address: '서울 용산구 효창원로69길 25 1층 mtl',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '효창동',
    subway: '효창공원앞역',
    wifi: 'O',
    pet: 'O',
    description: '???',
  },
  {
    name: '에이프릴커피',
    address: '서울 용산구 이태원로54길 19',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '한남동',
    subway: '한강진역',
  },
  {
    name: '메쉬커피 해방촌',
    address: '서울 용산구 신흥로7길 10 1층',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '용산동2가',
    subway: '녹사평역',
  },
  {
    name: '데일리루틴',
    address: '서울 용산구 한강대로84길 5-8 데일리루틴',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '남영동',
    subway: '숙대입구역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '오르소에스프레소바',
    address: '서울 용산구 두텁바위로1길 107 1층 105호',
    sido: '서울특별시',
    gungu: '용산구',
    dong: '후암동',
    subway: '숙대입구역',
    pet: 'O',
  },
  {
    name: '와이엠 에스프레소 룸(YM ESPRESSO ROOM)',
    address: '서울 은평구 진관3로 43-9 래미안 909동 1층 상가 101호',
    sido: '서울특별시',
    gungu: '은평구',
    dong: '진관동',
    subway: '구파발역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '톤티커피',
    address: '서울 종로구 북촌로 6-8 톤티커피',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '재동',
    subway: '안국역',
    wifi: 'O',
    tags: '로스터리,밸런스',
    description:
      '*대표메뉴*\n\n1.고소한 우유베이스+크림+에스프레소가 어우러진 아인슈페너 - 톤티베이비\n2.해가 지는 모습처럼 아름답고 청량+달달한 주스\n- 비포선셋\n\n(+그외 다양한 음료,디저트, 핸드드립, 드립백, 더치커피도 판매중\n/ take out 1000원 할인)',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20210803_209%2F1627996242580ov4oU_JPEG%2Fz61sdTfCf-670B5S-uPng7bp.jpeg.jpg',
    'images.1':
      'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fbk6Ixs%2FbtrukfIx040%2FrBI3ucXeCp3ARXlPuuqMAk%2Fimg.png',
  },
  {
    name: '카타딘',
    address: '서울 종로구 북촌로 31-6 1층',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '가회동',
    subway: '안국역',
    description:
      '디저트와 함께 필터커피, 차를 판매하고 있습니다.\n머무르는 시간동안 언제나 모두에게 담담한 휴식시간이 되길 바라고 있습니다.\n작은 공간으로 조용한 대화 부탁드리겠습니다. 감사합니다.\n\n당일 디저트 재료 소진 및 상황에 따라 운영시간의\n변동이 있는 점 양해 부탁드리겠습니다',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA2MjFfMTI1%2FMDAxNjU1Nzk0NTE2NjYy.N1MvudOVebAxarEoVF7Yf414bDXQ8uAGp4fJyoqTOCkg.EjWdL0gwXe8UsO4g3IjCWCuD_a26o-jAKNYujTaCOkIg.JPEG.roll5905%2F1.jpg',
    'images.1':
      'https://mblogthumb-phinf.pstatic.net/MjAyMjA4MjJfOTYg/MDAxNjYxMTY0MjUwODk5.NcbQEsjSaNXGk75346Lb6-lRPndT2kPnahMONMS-Anwg.0qR0NiTQOWIjKiJnE8GvelsoFWBlHQ1tngQCYm8edsYg.JPEG.506gywjd/IMG_0489.jpg?type=w800',
  },
  {
    name: '파스텔커피웍스 서촌점',
    address: '서울 종로구 필운대로3길 2',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '누하동',
    subway: '경복궁역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리,스페셜티',
    description: '*대표메뉴*\n\n - 샹티샹티',
    'images.0':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjAyMjRfMTYg%2FMDAxNjQ1Njk3ODQ0MTgy.zPjuovEVhXaXSH8NNrAzkJB1oTpX5UnxKXLJFDQR4gwg.Q7VL6le3hc07jSOrP6s6DoB50OMfdjtJwpUVn8gSzLkg.JPEG.iambine2fc%2Foutput_2823515295.jpg',
    'images.1':
      'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbZbgwF%2FbtraInRGHJR%2FFzxQUlr0wvgq669WC6ZkT1%2Fimg.jpg',
  },
  {
    name: '에디션덴마크쇼룸',
    address: '서울 종로구 자하문로9길 24 1층',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '통인동',
    subway: '경복궁역',
    wifi: 'O',
    tags: '로스터리,스페셜티',
    description:
      '에디션덴마크가 소개하는 덴마크 커피, 티, 꿀 제품을 경험할 수 있는 쇼룸 공간입니다.',
    'images.0':
      'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200707_81%2F1594126084213phlMJ_JPEG%2FS55APmL3gwNNtzXyDz0WTRKW.JPG.jpg',
    'images.1':
      'https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjA2MDJfOTQg%2FMDAxNjU0MTYyMzY0Nzc1.BNrSJwpW471GagI3zZwv-jSuhhV3n1RnbxW7PBr5Fmgg.qx42Em91WzRjEBZV11j5IULjobkDfeoU8diJgwxUcwMg.JPEG.gerbera__%2FIMG_4729.jpg',
  },
  {
    name: '리셉션',
    address: '서울 종로구 자하문로 70 1층일부(효자동, 효자빌딩)',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '효자동',
    subway: '경복궁역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: 'TXT Coffee',
    address: '서울 종로구 창덕궁길 121',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '원서동',
    subway: '안국역',
    wifi: 'O',
  },
  {
    name: '결',
    address: '서울 종로구 우정국로 26',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '공평동',
    subway: '종각역',
    wifi: 'O',
  },
  {
    name: '프릳츠 원서점',
    address: '서울 종로구 율곡로 83 아라리오 뮤지엄',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '원서동',
    subway: '안국역',
    wifi: 'O',
    description: '???',
  },
  {
    name: '에이커피 서울',
    address: '서울 종로구 백석동1가길 19',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '부암동',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '카페 E to E',
    address: '서울 종로구 수표로 86-1 2F 카페 E to E',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '관수동',
    subway: '종로3가역',
    wifi: 'O',
  },
  {
    name: '서울상회',
    address: '서울 종로구 우정국로2길 17 동강빌딩 3층',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '관철동',
    subway: '종각역',
  },
  {
    name: '헤르만의정원 광화문점',
    address: '서울 종로구 종로3길 17 1층 소호거리 111호',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '청진동',
    subway: '광화문역',
  },
  {
    name: '나무사이로',
    address: '서울 종로구 사직로8길 21 카페 나무사이로',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '내자동',
    subway: '경복궁역',
    wifi: 'O',
  },
  {
    name: '쏘리에스프레소바',
    address: '서울 종로구 자하문로2길 12 1층',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '적선동 ',
    subway: '경복궁역 ',
  },
  {
    name: '커넥트계동',
    address: '서울 종로구 계동길 72 카페 커넥트계동',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '계동',
    subway: '안국역',
    wifi: 'O',
  },
  {
    name: '라콜롬브',
    address: '서울 종로구 대학로12길 83',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '동숭동',
    subway: '혜화역',
    tags: '로스터리',
  },
  {
    name: '커피한약방 혜화점',
    address: '서울 종로구 동숭2길 9',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '동숭동',
    subway: '혜화역',
    wifi: 'O',
  },
  {
    name: '동숭동커피',
    address: '서울 종로구 동숭3길 6-4 동숭동커피',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '동숭동',
    subway: '혜화역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '체리 빈 커피',
    address: '서울 종로구 혜화로2길 10 1층',
    sido: '서울특별시',
    gungu: '종로구',
    dong: '혜화동',
    subway: '혜화역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '커피스니퍼 시청점',
    address: '서울 중구 세종대로16길 27 남양빌딩 1층 102호',
    sido: '서울특별시',
    gungu: '중구',
    dong: '북창동',
    subway: '시청역',
    wifi: 'O',
    pet: 'O',
    description: '???',
  },
  {
    name: '블루보틀 명동 카페',
    address: '서울 중구 명동길 14 1층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '명동2가',
    subway: '을지로입구역',
  },
  {
    name: '로투스',
    address: '서울 중구 삼일대로9길 6',
    sido: '서울특별시',
    gungu: '중구',
    dong: '저동1가',
    subway: '명동역',
  },
  {
    name: '커피인쇄소',
    address: '서울 중구 퇴계로27길 12-5 (2층)',
    sido: '서울특별시',
    gungu: '중구',
    dong: '필동1가',
    subway: '충무로역',
  },
  {
    name: '엘까페씨또바',
    address: '서울 중구 동호로11가길 25 1층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '신당동',
    subway: '약수역',
    wifi: 'O',
  },
  {
    name: '리사르커피',
    address: '서울 중구 다산로8길 16-7',
    sido: '서울특별시',
    gungu: '중구',
    dong: '신당동',
    subway: '약수역',
    tags: '로스터리',
  },
  {
    name: '보헤이 커피',
    address: '서울 중구 동호로15가길 15 1층 보헤이 커피',
    sido: '서울특별시',
    gungu: '중구',
    dong: '신당동',
    subway: '약수역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '알디비케이 커피 쇼룸(RDBK COFFEE SHOW ROOM)',
    address: '서울 중구 동호로17길 13 1층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '신당동',
    subway: '동대입구역',
    wifi: 'O',
    pet: 'O',
  },
  {
    name: '헤베커피',
    address: '서울 중구 필동로 32 낙원빌딩 1층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '필동2가',
    subway: '충무로역',
    wifi: 'O',
    pet: 'O',
    tags: '로스터리',
  },
  {
    name: '노띵커피',
    address: '서울 중구 퇴계로50길 33-2',
    sido: '서울특별시',
    gungu: '중구',
    dong: '묵정동',
    subway: '동대입구역',
  },
  {
    name: '섹터 커피 바',
    address: '서울 중구 퇴계로 198 2층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '필동2가',
    subway: '충무로역',
    wifi: 'O',
    tags: '로스터리',
  },
  {
    name: '에쏘피리언스',
    address: '서울 중구 수표로6길 24-1 1층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '충무로3가',
    subway: '충무로역',
    wifi: 'O',
  },
  {
    name: '몰또 이탈리안 에스프레소바',
    address: '서울 중구 명동길 73 3층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '명동1가',
    subway: '명동역',
  },
  {
    name: '커피사',
    address: '서울 중구 을지로 142-1 건물왼편 안쪽 3층',
    sido: '서울특별시',
    gungu: '중구',
    dong: '을지로3가',
    subway: '을지로3가역',
    wifi: 'O',
  },
  {
    name: '커피루소 정동',
    address: '서울 중구 정동길 17',
    sido: '서울특별시',
    gungu: '중구',
    dong: '정동',
    subway: '서대문역',
    wifi: 'O',
  },
  {
    name: '테바커피',
    address: '서울 중랑구 중랑천로12길 83 수령골든팰리스 1층 101호',
    sido: '서울특별시',
    gungu: '중랑구',
    dong: '상봉동',
    subway: '중랑역',
    wifi: 'O',
  },
  {
    name: '더반 여의도',
    address: '서울 영등포구 여의대로 108 더현대 서울 B1',
    sido: '서울특별시',
    gungu: '영등포구',
    dong: '여의도동',
    subway: '여의나루역',
    parking: 'O',
  },
  {
    name: '티에프티 여의도',
    address: '서울 영등포구 여의대방로67길 11 잡지회관 1층, 2층',
    sido: '서울특별시',
    gungu: '영등포구',
    dong: '여의도동',
    subway: '여의나루역',
  },
];
export default mania_cafes_data;
